$(window).on('load',function(){$("#preloader").fadeOut("slow");});$(window).resize(function(){$('.intro-inner').css('margin-top',$('#header').css('height'));$('.full-height').innerHeight($(window).height());}).resize();$(function(){$('.dropdown-toggle').parent().hover(function(){var menu=$('> .dropdown-menu',this);var menupos=$(menu).offset();if(menupos.left+menu.width()>$(window).width()){var newpos=-$(menu).width();menu.css({left:newpos});}});$(document).ready(function(){$(".mlc").on('click',function(event){$(".navbar-collapse").collapse('hide');});});});'use strict';(function(factory){if(typeof define=='function'&&define.amd){define(['jquery'],factory);}
else if(typeof exports=='object'){module.exports=factory(require('jquery'));}
else{factory(jQuery);}})(function($){var desc=':not(.disabled, .divider, .dropdown-header)';function Submenupicker(element){this.$element=$(element);this.$main=this.$element.closest('.dropdown, .dropup, .btn-group');this.$menu=this.$element.parent();this.$drop=this.$menu.parent().parent();this.$menus=this.$menu.siblings('.dropdown-submenu');var $children=this.$menu.find('> .dropdown-menu > '+desc);this.$submenus=$children.filter('.dropdown-submenu');this.$items=$children.not('.dropdown-submenu');this.init();}
Submenupicker.prototype={init:function(){this.$element.on({'click.bs.dropdown':$.proxy(this.click,this),keydown:$.proxy(this.keydown,this)});this.$menu.on('hide.bs.submenu',$.proxy(this.hide,this));this.$items.on('keydown',$.proxy(this.item_keydown,this));this.$menu.nextAll(desc+':first:not(.dropdown-submenu)').children('a').on('keydown',$.proxy(this.next_keydown,this));},click:function(event){event.stopPropagation();this.toggle();},toggle:function(){if(this.$menu.hasClass('open')){this.close();}
else{this.$menu.addClass('open');this.$menus.trigger('hide.bs.submenu');}},hide:function(event){event.stopPropagation();this.close();},close:function(){this.$menu.removeClass('open');this.$submenus.trigger('hide.bs.submenu');},keydown:function(event){if($.inArray(event.keyCode,[32,38,40])!=-1){event.preventDefault();}
if($.inArray(event.keyCode,[13,32])!=-1){this.toggle();}
else if($.inArray(event.keyCode,[27,38,40])!=-1){event.stopPropagation();if(event.keyCode==27){if(this.$menu.hasClass('open')){this.close();}
else{this.$menus.trigger('hide.bs.submenu');this.$drop.removeClass('open').children('a').trigger('focus');}}
else{var $items=this.$main.find('li:not(.disabled):visible > a');var index=$items.index(event.target);if(event.keyCode==38&&index!==0){index--;}
else if(event.keyCode==40&&index!==$items.length-1){index++;}
else{return;}
$items.eq(index).trigger('focus');}}},item_keydown:function(event){if(event.keyCode!=27){return;}
event.stopPropagation();this.close();this.$element.trigger('focus');},next_keydown:function(event){if(event.keyCode!=38){return;}
event.preventDefault();event.stopPropagation();var $items=this.$drop.find('li:not(.disabled):visible > a');var index=$items.index(event.target);$items.eq(index-1).trigger('focus');}};return $.fn.submenupicker=function(elements){var $elements=this instanceof $?this:$(elements);return $elements.each(function(){var data=$.data(this,'bs.submenu');if(!data){data=new Submenupicker(this);$.data(this,'bs.submenu',data);}});};});$('.dropdown-submenu > a').submenupicker();$(function(){$(".fullscreen-menu .menu-button").on('click',function(){$(".fullscreen-menu .menu-nav").fadeToggle(400);$(".hamburger .top-menu").toggleClass("top-animate");$(".hamburger .mid-menu").toggleClass("mid-animate");$(".hamburger .bottom-menu").toggleClass("bottom-animate");$(".show-hide-on-scroll").toggleClass("no-move");$("body").toggleClass("no-scroll");});$(".menu-nav li a").on('click',function(){$(".menu-button").click();});});$(function(){var didScroll;var lastScrollTop=0;var delta=2;var navbarHeight=$('.show-hide-on-scroll').outerHeight();$(window).scroll(function(event){didScroll=true;});setInterval(function(){if(didScroll){hasScrolled();didScroll=false;}},50);function hasScrolled(){var st=$(this).scrollTop();if(Math.abs(lastScrollTop-st)<=delta)
return;if(st>lastScrollTop&&st>navbarHeight){$('.show-hide-on-scroll').addClass('fly-up');}else{if(st+$(window).height()<$(document).height()){$('.show-hide-on-scroll').removeClass('fly-up');}}
lastScrollTop=st;}});$(function(){var cbpAnimatedHeader=(function(){var docElem=document.documentElement,header=document.querySelector('#header'),didScroll=false,changeHeaderOn=1;function init(){window.addEventListener('scroll',function(event){if(!didScroll){didScroll=true;setTimeout(scrollPage,150);}},false);}
function scrollPage(){var sy=scrollY();if($(this).scrollTop()>150){$('#header.fixed-top, #header.show-hide-on-scroll').addClass("header-filled");}
else{$('#header.fixed-top, #header.show-hide-on-scroll').removeClass("header-filled");}
didScroll=false;}
function scrollY(){return window.pageYOffset||docElem.scrollTop;}
init();})();});$(function(){var megaDrop=$('.top-slidingbar-trigger');var megaContainer=$('#top-slidingbar');$(megaDrop).on('click',function(){$(megaContainer).slideToggle(300,function(){if($(this).is(":hidden"))$(megaDrop).html("+");else $(megaDrop).html("Ã—");});});});$(window).on('load',function(){new WOW().init();});$(function(){$('.sm-scroll').on('click',function(){if(location.pathname.replace(/^\//,'')===this.pathname.replace(/^\//,'')&&location.hostname===this.hostname){var target=$(this.hash);target=target.length?target:$('[name='+this.hash.slice(1)+']');if(target.length){$('html,body').animate({scrollTop:target.offset().top},1500,'easeInOutExpo');return false;}}});});$(function(){var $container=$('.isotope-items-wrap');$container.imagesLoaded(function(){$container.isotope({itemSelector:'.isotope-item',transitionDuration:'0.5s',masonry:{columnWidth:'.grid-sizer',horizontalOrder:false}});});$('.isotope-filter-links a').on('click',function(){var selector=$(this).attr('data-filter');$container.isotope({filter:selector});return false;});var filterItemActive=$('.isotope-filter-links a');filterItemActive.on('click',function(){var $this=$(this);if(!$this.hasClass('active')){filterItemActive.removeClass('active');$this.addClass('active');}});});$(function(){if(!jQuery.browser.mobile)
$(".youtube-bg").mb_YTPlayer();});$(function(){$('.owl-carousel').each(function(){var $carousel=$(this);$carousel.owlCarousel({items:$carousel.data("items"),loop:$carousel.data("loop"),margin:$carousel.data("margin"),center:$carousel.data("center"),startPosition:$carousel.data("start-position"),animateIn:$carousel.data("animate-in"),animateOut:$carousel.data("animate-out"),autoWidth:$carousel.data("autowidth"),autoHeight:$carousel.data("autoheight"),autoplay:$carousel.data("autoplay"),autoplayTimeout:$carousel.data("autoplay-timeout"),autoplayHoverPause:$carousel.data("autoplay-hover-pause"),autoplaySpeed:$carousel.data("autoplay-speed"),nav:$carousel.data("nav"),navText:['<i class="fa fa-chevron-left"></i>','<i class="fa fa-chevron-right"></i>'],navSpeed:$carousel.data("nav-speed"),dots:$carousel.data("dots"),dotsSpeed:$carousel.data("dots-speed"),mouseDrag:$carousel.data("mouse-drag"),touchDrag:$carousel.data("touch-drag"),dragEndSpeed:$carousel.data("drag-end-speed"),lazyLoad:$carousel.data("lazy-load"),video:true,responsive:{0:{items:$carousel.data("mobile-portrait"),center:false,},480:{items:$carousel.data("mobile-landscape"),center:false,},768:{items:$carousel.data("tablet-portrait"),center:false,},992:{items:$carousel.data("tablet-landscape"),},1200:{items:$carousel.data("items"),}}});});});$(function(){var isMobile={Android:function(){return navigator.userAgent.match(/Android/i);},BlackBerry:function(){return navigator.userAgent.match(/BlackBerry/i);},iOS:function(){return navigator.userAgent.match(/iPhone|iPad|iPod/i);},Opera:function(){return navigator.userAgent.match(/Opera Mini/i);},Windows:function(){return navigator.userAgent.match(/IEMobile/i);},any:function(){return(isMobile.Android()||isMobile.BlackBerry()||isMobile.iOS()||isMobile.Opera()||isMobile.Windows());}};jQuery(document).ready(function(){if(!isMobile.any()){(function($){$.fn.parallax=function(options){var windowHeight=$(window).height();var settings=$.extend({speed:0.5},options);return this.each(function(){var $this=$(this);$(document).scroll(function(){var scrollTop=$(window).scrollTop();var offset=$this.offset().top;var height=$this.outerHeight();if(offset+height<=scrollTop||offset>=scrollTop+windowHeight){return;}
var yBgPosition=Math.round((offset-scrollTop)*settings.speed);$this.css('background-position','center '+yBgPosition+'px');});});}}(jQuery));$('.bg-image-parallax').css('background-attachment','fixed');$('.bg-image-parallax').parallax({speed:0.5});}});});function init(){var vidDefer=document.getElementsByTagName('iframe');for(var i=0;i<vidDefer.length;i++){if(vidDefer[i].getAttribute('data-src')){vidDefer[i].setAttribute('src',vidDefer[i].getAttribute('data-src'));}}}
window.onload=init;$(document).ready(function(){$('.popup-gallery').magnificPopup({delegate:'.popup-trigger',type:'image',tLoading:'Loading image #%curr%...',mainClass:'mfp-fadein',gallery:{enabled:true,preload:[0,1],navigateByImgClick:true,arrowMarkup:'<button title="%title%" type="button" class="mfp-custom-arrow mfp-custom-arrow-%dir%"></button>',tPrev:'Previous (Left arrow key)',tNext:'Next (Right arrow key)',tCounter:'<span class="mfp-counter">%curr% of %total%</span>'},image:{titleSrc:'data-title',tError:'<a href="%url%">The image #%curr%</a> could not be loaded.'}});$('.inline-popup-trigger').magnificPopup({type:'inline',modal:false,alignTop:true,fixedContentPos:true,fixedBgPos:false,overflowY:'auto',closeBtnInside:true,preloader:false,midClick:true,removalDelay:300,mainClass:'mfp-fade-zoom',gallery:{enabled:true,arrowMarkup:'<button title="%title%" type="button" class="mfp-custom-arrow mfp-custom-arrow-%dir%"></button>',tPrev:'Previous (Left arrow key)',tNext:'Next (Right arrow key)'}});$(document).on('click','.inline-popup-close',function(e){e.preventDefault();$.magnificPopup.close();});});$(function(){$("#contact-form").submit(function(){var th=$(this);$.ajax({type:"POST",url:"mail.php",data:th.serialize()}).done(function(){alert("Thank you. Your message has been sent!");setTimeout(function(){th.trigger("reset");},1000);});return false;});});$(window).scroll(function(){if($(this).scrollTop()>400){$('.scrolltotop').fadeIn();}else{$('.scrolltotop').fadeOut();}});